(setq xml-file "/home/rohan/tmp/userDefinedLanguages-master/UDLs/Cisco_IOS_byLuisPisco.xml")
(setq base-table 'java-mode-syntax-table)
(setq comment-string "//")
(setq base-mode 'java-mode)
(setq conversion
                                        ; An assoc-list of the form (kw1 . font-lock-whatever-face)
      '(
        ("Keywords1" . font-lock-type-face)
        ("Keywords2" . font-lock-constant-face)
        ("Keywords3" . font-lock-builtin-face)
        ("Keywords4" . font-lock-keyword-face)
        ("Keywords5" . font-lock-reference-face)
        ("Keywords6" . font-lock-warning-face)
        ("Keywords7" . font-lock-type-face)
        ("Keywords8" . font-lock-constant-face)

        ("Words1" . font-lock-type-face)
        ("Words2" . font-lock-constant-face)
        ("Words3" . font-lock-builtin-face)
        ("Words4" . font-lock-keyword-face)
        ("Words5" . font-lock-reference-face)
        ("Words6" . font-lock-warning-face)
        ("Words7" . font-lock-type-face)
        ("Words8" . font-lock-constant-face)
        ))
